# Generated by Django 4.1.1 on 2022-09-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('doc', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('about', models.TextField(verbose_name='Sobre')),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('site', models.CharField(max_length=14, verbose_name='Site')),
            ],
        ),
    ]
