# Generated by Django 4.1.1 on 2022-09-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.CreateModel(
            name='Offert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_costumer', models.CharField(max_length=30, verbose_name='ID Cliente')),
                ('to', models.CharField(max_length=30, verbose_name='Para')),
                ('initial_value', models.BooleanField(verbose_name='Ativo')),
                ('amount', models.FloatField(max_length=10, verbose_name='Quantidade')),
                ('amount_type', models.CharField(choices=[('1', 'ton'), ('2', 'kg'), ('3', 'g'), ('4', 'un')], default='1', max_length=4, verbose_name='Un. de medida')),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.client', verbose_name='De')),
            ],
        ),
    ]
