# Generated by Django 4.1.1 on 2022-09-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_company_options_offert'),
    ]

    operations = [
        migrations.AddField(
            model_name='offert',
            name='value_type',
            field=models.CharField(choices=[('1', '$'), ('2', 'R$')], default='2', max_length=4, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='offert',
            name='From',
            field=models.CharField(max_length=30, verbose_name='De'),
        ),
        migrations.AlterField(
            model_name='offert',
            name='id_costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.client', verbose_name='ID Cliente'),
        ),
        migrations.AlterField(
            model_name='offert',
            name='initial_value',
            field=models.FloatField(max_length=10, verbose_name='Valor inicial'),
        ),
    ]
