# Generated by Django 4.1.1 on 2022-09-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_id_costumer_offert_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.client', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(max_length=10, verbose_name='Valor inicial')),
                ('amount', models.FloatField(max_length=10, verbose_name='Quantidade')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.offert', verbose_name='Oferta')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.company', verbose_name='Empresa')),
            ],
        ),
    ]
