# Generated by Django 4.1.1 on 2022-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_offert_costumer_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.FloatField(max_length=10, verbose_name='Valor'),
        ),
    ]
