# Generated by Django 4.1.1 on 2022-09-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_bid_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offert',
            name='costumer',
            field=models.CharField(choices=[('12', '12'), ('13', '13')], max_length=50, verbose_name='Cliente id'),
        ),
    ]
