# Generated by Django 4.1.1 on 2022-09-20 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_offert_costumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='offer',
        ),
        migrations.AddField(
            model_name='bid',
            name='offert',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('6', '6'), ('7', '7')], default=django.utils.timezone.now, max_length=50, verbose_name='Offert id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='provider',
            field=models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('2', '2')], max_length=50, verbose_name='Provider id'),
        ),
    ]
